feat: add a reposition contract function on reposition
gnoswap-labs/gnoswap-interface pull request #427
Opened 2024-07-16 11:16 UTC by jinoosss

# Descriptions

Add a reposition contract function on reposition.

2024-07-16 13:35 UTC, dongwon8247 requested changes

2024-07-16 13:35 UTC, dongwon8247 commented on packages/web/src/hooks/reposition/use-reposition-handle.tsx
> +        ).toNumber() * 0.95,
shouldn't it be `0.995`? the default slippage is 0.5%

2024-07-16 13:36 UTC, dongwon8247 commented on packages/web/src/hooks/reposition/use-reposition-handle.tsx
> +        ).toNumber() * 0.95,
my bad 0.95 is correct

2024-07-16 13:36 UTC, dongwon8247 submitted a review, later dismissed

2024-07-17 00:50 UTC, AkydA approved these changes

2024-07-17 10:22 UTC, AkydA approved these changes

2024-07-17 10:25 UTC, merged